name: CD

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply Terraform and deploy (manual run)"
        type: boolean
        default: false
        required: false
      build_backend_image:
        description: "Build & Push backend image (manual run)"
        type: boolean
        default: false
        required: false
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Aciona o deploy quando uma nova tag com formato vX.Y.Z for criada

permissions:
  contents: read  # Permissões para acessar os conteúdos do repositório

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Fallback de região se o secret não estiver definido
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID || '058264220517' }}
      ECR_REPO_BACKEND: ${{ secrets.ECR_REPO_BACKEND || 'devops-study-backend'}}
    steps:
      # Passo 1: Checkout do código
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Preflight secrets check
        env:
          S_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S_AWS_REGION: ${{ secrets.AWS_REGION }}
          S_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          S_ECR_REPO_BACKEND: ${{ secrets.ECR_REPO_BACKEND }}
        run: |
          missing=0
          if [ -z "${S_AWS_ACCESS_KEY_ID}" ]; then echo "::error::Missing secret AWS_ACCESS_KEY_ID"; missing=1; fi
          if [ -z "${S_AWS_SECRET_ACCESS_KEY}" ]; then echo "::error::Missing secret AWS_SECRET_ACCESS_KEY"; missing=1; fi
          if [ -z "${S_AWS_REGION}" ]; then echo "::warning::Missing AWS_REGION; defaulting to us-east-1"; fi
          if [ -z "${S_AWS_ACCOUNT_ID}" ]; then echo "::warning::Missing AWS_ACCOUNT_ID (required for ECR build/push)"; fi
          if [ -z "${S_ECR_REPO_BACKEND}" ]; then echo "::warning::Missing ECR_REPO_BACKEND (required for ECR build/push)"; fi
          test "$missing" -eq 0

      # Passo 2: Configurar as credenciais AWS com Access Key ID e Secret Access Key
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use o Access Key ID armazenado no GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use o Secret Access Key armazenado no GitHub Secrets
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
      - name: Verify AWS identity and region
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "Error: AWS credentials are not properly configured in repository secrets"
            echo "Please add the following secrets to your repository:"
            echo "- AWS_ACCESS_KEY_ID"
            echo "- AWS_SECRET_ACCESS_KEY"
            echo "- AWS_REGION"
            echo "- AWS_ACCOUNT_ID"
            echo "- ECR_REPO_BACKEND"
            exit 1
          fi
      - name: Verify required environment variables
        run: |
          if [ -z "$AWS_ACCOUNT_ID" ]; then
            echo "Error: AWS_ACCOUNT_ID secret is not configured"
            exit 1
          fi
          if [ -z "$ECR_REPO_BACKEND" ]; then
            echo "Error: ECR_REPO_BACKEND secret is not configured"
            exit 1
          fi
          echo "All required secrets are configured successfully"

      # Passo 3: Login no Amazon ECR
      - name: Login to Amazon ECR
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.build_backend_image == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: aws-actions/amazon-ecr-login@v2
      # Garante que o repositório do ECR existe
      - name: Ensure ECR repository exists
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.build_backend_image == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPO_BACKEND" >/dev/null 2>&1 \
            || aws ecr create-repository --repository-name "$ECR_REPO_BACKEND"

      # Passo 4: Build & Push Backend para o ECR #
      - name: Build & Push Backend to ECR
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.build_backend_image == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          IMAGE_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_BACKEND"
          IMAGE_TAG="${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}"
          docker build -t "$IMAGE_REPO:latest" -t "$IMAGE_REPO:$IMAGE_TAG" ./backend
          docker push "$IMAGE_REPO:latest"
          docker push "$IMAGE_REPO:$IMAGE_TAG"

      # Passo 5: Terraform (se necessário, caso queira gerenciar a infraestrutura via Terraform)
      # Configuração do Terraform para aplicar a infraestrutura (caso tenha)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init/Plan
        working-directory: infra/terraform
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_container_image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_BACKEND }}:latest
        run: |
          terraform init -input=false
          terraform plan -input=false -out=tfplan

      # Passo 6: Aplicar Terraform (gerenciar infraestrutura como código)
      - name: Terraform Apply (manual/condicional)
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        working-directory: infra/terraform
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_container_image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_BACKEND }}:latest
        run: terraform apply -input=false -auto-approve tfplan

      # Ler outputs do Terraform (após apply) e realizar deploy
      - name: Read Terraform outputs
        id: tfout
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        working-directory: infra/terraform
        run: |
          echo "bucket=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "cluster=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
          echo "service=$(terraform output -raw ecs_service_name)" >> $GITHUB_OUTPUT
          echo "cf_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT
          echo "cf_domain=$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_OUTPUT

      - name: Deploy ECS service
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          aws ecs update-service --cluster "${{ steps.tfout.outputs.cluster }}" --service "${{ steps.tfout.outputs.service }}" --force-new-deployment

      - name: Setup Node (frontend build)
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Build frontend
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          npm run build

      - name: Upload Frontend to S3
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          aws s3 sync ./frontend/dist/ s3://${{ steps.tfout.outputs.bucket }} --delete

      - name: Invalidate CloudFront cache
        if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && inputs.apply == 'true') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          aws cloudfront create-invalidation --distribution-id "${{ steps.tfout.outputs.cf_id }}" --paths "/*"
